# Site settings
title: 610YesNoLovely
email: harv.thompson@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  610 - Harvey is 6 foot 10 inches tall.<br>
  Yes - His parents are tall.<br>
  No - He does not play basketball.<br>
  Lovely - The weather is lovely up here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.610yesnolovely.org" # the base hostname & protocol for your site
twitter_username: 610yesnolovely
github_username:  harveyt

# Build settings
markdown: kramdown
gems:
  - octopress-codefence
  - octopress-solarized

